USE [master]
GO

/****** Object:  Database [DapperEmpDeptDb]    ******/
CREATE DATABASE [DapperEmpDeptDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DapperEmpDeptDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DapperEmpDeptDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DapperEmpDeptDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DapperEmpDeptDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DapperEmpDeptDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DapperEmpDeptDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DapperEmpDeptDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DapperEmpDeptDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DapperEmpDeptDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DapperEmpDeptDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DapperEmpDeptDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DapperEmpDeptDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DapperEmpDeptDb] SET  MULTI_USER 
GO

ALTER DATABASE [DapperEmpDeptDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DapperEmpDeptDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DapperEmpDeptDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DapperEmpDeptDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DapperEmpDeptDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DapperEmpDeptDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DapperEmpDeptDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DapperEmpDeptDb] SET  READ_WRITE 
GO


USE [DapperEmpDeptDb]
GO

/****** Object:  Table [dbo].[Departments]    Script Date: 25-09-2021 7.50.51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Departments](
	[DeptId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Departments] PRIMARY KEY CLUSTERED 
(
	[DeptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO




USE [DapperEmpDeptDb]
GO

/****** Object:  Table [dbo].[Employees]    Script Date: 25-09-2021 7.51.21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employees](
	[EmpId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Address] [varchar](250) NOT NULL,
	[ImagePath] [varchar](250) NOT NULL,
	[DeptId] [int] NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[EmpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [FK_Employees_Departments_DeptId] FOREIGN KEY([DeptId])
REFERENCES [dbo].[Departments] ([DeptId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [FK_Employees_Departments_DeptId]
GO

